### PR TITLE
Myriad of Fixes

### LINKED ISSUE #8: 3 Stock Crash in Health Graph?

### LINKED ISSUE #11: "That model is not found" for stream match renders nothing for matchup view
Should render match anyway.

### LINKED ISSUE #12: 3-stock shows "NaN%"
Should show "N/A"

### PR DESCRIPTION
**Pull request by jack-michaud**
- Adds banjo and kazooie 
- Fix #11 by only fetching necessary resource
- Fix #8, only include stocks in latestTime calc if there are any
- Fix #12, don't round 'N/A' to the first 3 digits and you won't get "NaN%"

### CODE REVIEW

File: src/default/DefaultWrap.js [hunk 1]
```diff
@@ -27,12 +27,14 @@ class DefaultWrap extends SharedWrapMixin {
...
   }
 
-  render() {
+  render(props) {
     const { config, matchStats, setStats, theme } = this.state;
 
     return (
       <div className="App" style={{ width: '1920px', height: '1080px', overflow: 'hidden' }}>
-        { matchStats && setStats && config && theme &&
+        { !(this.props.shouldFetchMatch && !matchStats)
```
Comment (phytoporg) [inline src/default/DefaultWrap.js]: Oh-- is this the logic you were working out on the whiteboard? I see why this was tricky, ha.

File: src/xsplit/XsplitWrap.js [hunk 2]
```diff
@@ -62,7 +62,9 @@ class XsplitWrapper extends SharedWrapMixin {
 
     return (
       <div className="App" style={{ width: '1920px', height: '1080px', overflow: 'hidden' }}>
-        { matchStats && setStats && config && theme && configLoaded &&
+        { !(this.props.shouldFetchMatch && !matchStats)
```
Comment (phytoporg) [inline src/xsplit/XsplitWrap.js]: After looking at this a few times I'm wondering if maybe you should bundle this into a utility/helper function for readability. Maybe wrap this logic into a `ShouldAndCanFetchMatchSetStats()`?

Comment (jack-michaud) [reply src/xsplit/XsplitWrap.js]: Even demorgansing this would make it more clear. made an issue
